### ISSUE TITLE
Start

### ISSUE THREAD

**Issue by marcelomatz** [desenvolvedoresweb/notfound#1]
Excelente ideia. Acredito que podemos criar algo a nível nacional, e regionalizar as campanhas. Pensa na situação onde uma criança perdida tem a sua foto publicada na página 404. Se for uma criança do estado de Santa Catarina por exemplo, a foto dela deve aparecer com mais intensidade nos estados do sul (RS, SC, PR).

Se o mesmo acontecer na Bahia, deve se exibir a foto na região, onde a probabilidade de encontrar essa criança seja maior. E assim por diante.

Outro fator: Incentivar os sites a colocarem no menu a opção ' Página 404 ', e oferecer a opção ao usuário de visualizar uma página de erro, com a foto de alguma criança desaparecida.

Incluir a possibilidade de enviar informações de forma anônima, encaminhando a mesma para a delegacia mais próxima da região onde a criança foi avistada. Mandar para a delegacia um resumo do caso, informado no momento do cadastro da foto, para facilitar a compreensão da situação, e permitir uma ação mais rápida da polícia.

-->> Alguém tem números estatísticos? Sabe quantas crianças desaparecidas tem hoje no Brasil?

->> Quantas crianças são cadastradas no sistema de desaparecidos da justiça, todos os dias?

O que você acha disso, @germchaos ?

**Comment by bernardodiasc** [comment]
Só pra registro, segue o link da discussão origem https://plus.google.com/u/0/104670266773932503167/posts/1du8F8GZqN7

@matzemb acho bacana tudo isso. primeiro precisamos começar do começo. já iniciei uns testes no meu fork https://github.com/germchaos/notfound/tree/develop

esse projeto da pra fazer muuuuuuito rapido, só precisamos conseguir acesso ao banco de dados do governo, se conseguirmos acesso a um XML atualizado vai ser perfeito.

to aguardando mais informações do @highlabs sobre o projeto.

**Comment by marcelomatz** [comment]
Acho que podemos fechar essa issue ':)
